### ISSUE TITLE
Spectator list

### ISSUE THREAD

**Issue by DonMonro** [CowNowK/AimStar#104]
Can anyone help or guide me to use this?

`https://www.unknowncheats.me/forum/counter-strike-2-a/595247-spectator-list-2.html`

is this work even ?

**Comment by hahahahda325** [comment]
for external idk maybe u should try

**Comment by Nx0Ri** [comment]
Copy of [#98](https://github.com/CowNowK/AimStar/issues/89) issue

**Comment by Wuemeli** [comment]
CAN BE CLOSED ig

**Comment by Wuemeli** [comment]
@M3351AN

**Comment by CowNowK** [comment]
added
