### ISSUE TITLE
selling aimstar XD

### ISSUE THREAD

**Issue by ZuhuInc** [CowNowK/AimStar#111]
some guy trying to sell aimstar but clipping all screens to hiude the name
(https://1cheats.com/forums/topic/34-strikeover/)

**Comment by vsaint1** [comment]
i looked at his shit ( pre-made/stolen also  )  website valorant section and i cried laughing, screen-shots and videos from staffbesting 😂 , thx for sharing.

**Comment by twichbatchtvbatchfile** [comment]
LAMO

**Comment by Olgierd10** [comment]
he probably gonna install a virus on it and thats all XD
