### ISSUE TITLE
Using SG 553 bugs out the draw fov option

### ISSUE THREAD

**Issue by M4zeRain** [CowNowK/AimStar#113]
I think this happens with the Aug as well but i don't really know what exactly causes it so idk how to test it:
![AimStar_3 8-Patched_km7dfnk4t3](https://github.com/CowNowK/AimStar/assets/158751434/18469eeb-17bc-461d-bac7-4f41380c3f74)

**Comment by CowNowK** [comment]
Fixed with fov changer
