### ISSUE TITLE
Failed to update offsets.

### ISSUE THREAD

**Issue by thebeat1234** [CowNowK/AimStar#114]
It says when I open aimstar that it "Failed to update offsets." Is this because of the new CS2 update? Or did I somehow mess up the files?

**Comment by dexvinity** [comment]
> It says when I open aimstar that it "Failed to update offsets." Is this because of the new CS2 update? Or did I somehow mess up the files?

its the new cs2 it was just bad timing for the cheat

**Comment by thebeat1234** [comment]
Damn, thank you very much for telling me. Do you know when it might be back up and running per chance?

**Comment by sdclkja** [comment]
Hopefully it will be updated AinStar

**Comment by Olgierd10** [comment]
same

**Comment by CowNowK** [comment]
Updated and fixed

**Comment by rauljoseph85** [comment]
what was the update?
