### ISSUE TITLE
failed to get module adress

### ISSUE THREAD

**Issue by feddyofc** [CowNowK/AimStar#116]
idk how to fix this pls help
![Screenshot 2024-02-07 114740](https://github.com/CowNowK/AimStar/assets/159247771/bcac8e0f-c839-454a-a0e4-ada7bb9c321d)

**Comment by Nx0Ri** [comment]
run as admin

**Comment by getmad4love** [comment]
cs2 update ... we have to wait for new aimstar update

**Comment by slogo69** [comment]
i am running as admin but still getting same issue

**Comment by CowNowK** [comment]
Updated and fixed
