### ISSUE TITLE
Error: Failed To Load Assets After i installed it off here.

### ISSUE THREAD

**Issue by Olgierd10** [CowNowK/AimStar#119]
I Just Updated My CS2 Bc It Was A BIG Update and when i downloaded it today after exloader says it's currently unavailable bc of an update or a delete, and when i opened it up it said this: Failed To Load Update Assets Press Any Key To Continue...

**Comment by Nx0Ri** [comment]
![image](https://github.com/CowNowK/AimStar/assets/152011726/3491237b-8382-46dd-a51d-1416db3d6899)

**Comment by CowNowK** [comment]
because game updated, now fixed
