### ISSUE TITLE
Nova shotgun not showing 

### ISSUE THREAD

**Issue by Forsnoy** [CowNowK/AimStar#127]
An enemy with a nova shotgun is no longer visible on the ESP, he disappears as soon as he picks up the shotgun.

**Comment by Forsnoy** [comment]
set to GetWeaponName
char Buffer[525]{};
(the first random number that came to mind)
And everything worked :)

**Comment by CowNowK** [comment]
u can create a pr

**Comment by CowNowK** [comment]
Added
