### ISSUE TITLE
[error] failed to update offsets

### ISSUE THREAD

**Issue by DhG132** [CowNowK/AimStar#128]
[error] failed to update offsets

**Comment by DhG132** [comment]
Someone steals your files and charges for them, but their software doesn't have such problems
![Uploading 屏幕截图 2024-02-09 170348.png…]()

**Comment by CowNowK** [comment]
你用最新版了吗

**Comment by DhG132** [comment]
Is 4.0.3 the latest version

**Comment by DhG132** [comment]
没事了，必须先打开游戏后，抱歉麻烦你了
