### ISSUE TITLE
歹徒拿散彈槍, 瞄準機器人無法瞄準,不會開槍

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#130]
歹徒拿散彈槍,
瞄準機器人無法瞄準,不會開槍

**Comment by M3351AN** [comment]
已在提交中修補，等待發布或是自行構建
https://github.com/CowNowK/AimStar/commit/ae4cf03255a6c3f241c662d2134f40e106fa1385

**Comment by M3351AN** [comment]
https://github.com/CowNowK/AimStar/releases/tag/autobuild
在最近的自動構建版本中已經修補這個問題
