### ISSUE TITLE
It's request Can you increase fov 25 to 90 or 180 like Osiris also can you implement Rage features also include feature show spectator list. Include all Osiris feature that are missing.

### ISSUE THREAD

**Issue by koyande360** [CowNowK/AimStar#136]

**Comment by mildnsj** [comment]
Why would you even want rage for an external? So you can paste and sell?

**Comment by M3351AN** [comment]
> Why would you even want rage for an external? So you can paste and sell?

No toxic femboy

**Comment by koyande360** [comment]
can you put spectator list in aimstar.
