### ISSUE TITLE
Always RCS

### ISSUE THREAD

**Issue by JeepEda** [CowNowK/AimStar#138]
Is it because of the risk to create a function that always activates rcs?

**Comment by j621103** [comment]
啟動RCS
有什麼功能？
好像沒什麼變化

**Comment by JeepEda** [comment]
Rcs only works when the aimbot is working. I mean that always working RCS even when the aimbot is not working

**Comment by M3351AN** [comment]
The standalone RCS is not added simply because the code will get a bit complicated / lazy 2code, Maybe we'll add it in after a while

**Comment by JeepEda** [comment]
ahh i see thank you for answer me 'M3351AN'!!
