### ISSUE TITLE
V4.1

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#149]
1.自動瞄準 失效 (已經開啟,在圓圈範圍內,無法鎖定敵人,必須準心碰到對方才會開槍)
2.開啟無煙霧.  會導致閃退

**Comment by CowNowK** [comment]
自动瞄准机制更新为开火时瞄准，如果你需要使用旧的aimbot，请启用AimLock功能；新增了min fov，如果敌人在min fov内不会引起自瞄
无烟雾闪退暂时无法找到错误原因，我没有遇到这个情况
