### ISSUE TITLE
Aimbot: Prediction

### ISSUE THREAD

**Issue by TheGreenBandit** [CowNowK/AimStar#159]
Would help with snipers as currently the aimbot with snipers is quite dogshit.

**Comment by M3351AN** [comment]
There is no practical significance in implementing prediction in a external because it does not hook create_move
What's more, this is a game with subtick

**Comment by CowNowK** [comment]
create move externally lead to instant VAC

**Comment by TheGreenBandit** [comment]
Cant you just get the velocity of the other player and adjust off that?

**Comment by M3351AN** [comment]
why? In cs2, the desync between server and client less than 10ms + ping, and the network ping will be compensated by the server through backtrack. In fact, there is no need for prediction for the 10ms,it is less than 1 tick.

**Comment by TheGreenBandit** [comment]
> why? In cs2, the desync between server and client less than 10ms + ping, and the network ping will be compensated by the server through backtrack. In fact, there is no need for prediction for the 10ms,it is less than 1 tick.

Well prediction was my idea of fixing the snipers not working well with aimbot
