### ISSUE TITLE
rage for external

### ISSUE THREAD

**Issue by Dynamooo1** [CowNowK/AimStar#160]
https://github.com/dumitru1216/cs2-external-evo/tree/master/evo/hacks/features/ragebot
maybe add this bro so good option evo by dutu is a aimstar paste

**Comment by Loengames** [comment]
Yeah, I know that cheat.
It's got some cool features!

"Cow Now" I ask you to take a closer look at this cheat and take a couple of features from it.

**Comment by Loengames** [comment]
https://streamable.com/ds50sh

Here is an example of one function

https://yougame.biz/threads/310172/

**Comment by M3351AN** [comment]
it is 90% port from liv's base
in latest version of aimstar, u can did similiar with startbullet 0 & smooth 0.4 & auto shot

**Comment by Fr0go1** [comment]
> I'll say this a little rudely, reading the code and trying to implement it in your fork is often more useful than sitting in a gaming chair with a keyboard and complaining

What are you getting pressed for, I'm not complaining

**Comment by Fr0go1** [comment]
I couldn't give less of a shit if someone ports over more pasted code in to this cheat

**Comment by M3351AN** [comment]
> I couldn't give less of a shit if someone ports over more pasted code in to this cheat

that's not what I meant, I meant maybe focus more on understanding the code rather than listing too many todos

apologize for offending

**Comment by M3351AN** [comment]
https://streamable.com/1g2qvu
