### ISSUE TITLE
virus total say

### ISSUE THREAD

**Issue by codingnooblvl1** [CowNowK/AimStar#163]
Antiy-AVL
RiskWare/Win64.Gamehack
Avast
Win64:MiscX-gen [PUP]
Durchschnittlich
Win64:MiscX-gen [PUP]
DeepInstinct
BÖSISCH
ESET-NOD32
Eine Variante von Win64/GameHack.JE, potenziell unsicher
Fortinet
Adware/GameHack
Malwarebytes
Neshta.Virus.FileInfector.DDS
McAfee
Artemis!1E446D1C6F82
Microsoft
Trojaner:Win32/SuspExecRep.A!cl
Sophos
Generische Reputations-PUA (PUA)

**Comment by CowNowK** [comment]
A cheater fears his computer will be infected by an open-source program
🤣👉

**Comment by JannesBonk** [comment]
> Antiy-AVL
> RiskWare/Win64.Gamehack
> Avast
> Win64:MiscX-gen [PUP]
> Durchschnittlich
> Win64:MiscX-gen [PUP]
> DeepInstinct
> BÖSISCH
> ESET-NOD32
> Eine Variante von Win64/GameHack.JE, potenziell unsicher
> Fortinet
> Adware/GameHack
> Malwarebytes
> Neshta.Virus.FileInfector.DDS
> McAfee
> Artemis!1E446D1C6F82
> Microsoft
> Trojaner:Win32/SuspExecRep.A!cl
> Sophos
> Generische Reputations-PUA (PUA)

PUA - potential unwanted adware  ☠️
