### ISSUE TITLE
V4.2

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#169]
1.加載檔案, 會閃退 (win 10)
2.可以加入敵人會發光嗎
3.自動瞄準怪怪的,無法瞄準

**Comment by CowNowK** [comment]
这是发光
![image](https://github.com/CowNowK/AimStar/assets/133740174/5cf6d5f7-a52f-4ef4-9d74-aed235753ec9)

自瞄机制更新请参考:
[AimStar 4.1 Update Notes](https://github.com/CowNowK/AimStar/discussions/151)
