### ISSUE TITLE
AIM NOT WORKING

### ISSUE THREAD

**Issue by Dzilao33** [CowNowK/AimStar#175]
trigger working , but aim not.
after 4.1 revision my aim not working

**Comment by Dzilao33** [comment]
windows 11 pro
last version aim star
run admin perm
all .net installed

**Comment by blondedye** [comment]
> windows 11 pro
> 
> last version aim star
> 
> run admin perm
> 
> all .net installed
> 
> 

same thing 😅 ...

**Comment by CowNowK** [comment]
https://github.com/CowNowK/AimStar/discussions/151
