### ISSUE TITLE
add feature request😞

### ISSUE THREAD

**Issue by RaliVault** [CowNowK/AimStar#180]
I want to add psilent.
I can't possibly make it, but I think you can.
It may not be helpful, but I will post the site
https://www.iniuria.us/forum/showthread.php?32217-pSilent
plz sir.

**Comment by JannesBonk** [comment]
> I want to add psilent.
> I can't possibly make it, but I think you can.
> It may not be helpful, but I will post the site
> https://www.iniuria.us/forum/showthread.php?32217-pSilent
> plz sir.

pSilent is pretty much impossible on externals

**Comment by RaliVault** [comment]
omg...
