### ISSUE TITLE
cannot update offsets W11

### ISSUE THREAD

**Issue by ftdddfg** [CowNowK/AimStar#181]
title, lastest w11 build

**Comment by ftdddfg** [comment]
yes I tried with admin

**Comment by JannesBonk** [comment]
have you entered the OTP code?

**Comment by ftdddfg** [comment]
yeah, but today it didnt ask me to do it

**Comment by JannesBonk** [comment]
> yeah, but today it didnt ask me to do it 
> 

If I recall correctly, the *RELEASE* builds don't require you to put an OTP code in.
