### ISSUE TITLE
ban

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#183]
今天早上起來,被VAC鎖封了(ban),
VAC 說多位玩家檢舉,
當時玩的時候安全模式是關閉的
不知道是不是這個問題
現在我把安全模式打開了
不知道會改善嗎

順便一提
我在檢舉玩家的時候
每一個回合檢舉一次
同一名玩家的 steam-ID 號碼
都會不一樣
會變
這樣就保護的那位玩家
是嗎
我們的安全模式也會這樣嗎
tks

I woke up this morning and was banned by VAC.
VAC said that many players reported it,
When I was playing, I found out that safe mode was turned off.
No, that's not the problem
Now I have turned on safe mode
Don't know if it will improve?

Incidentally
When I report a player
Report once per round
The steam-ID number of the player with the same name
It will be different
will change
This protects that player
Yeah
Is this our safe model?
tks

**Comment by Nx0Ri** [comment]
此翻譯是使用谷歌翻譯完成的，可能不正確。

您好，是的，如果您不使用安全模式，您可能會被 VAC 禁止。

Valve 不會做出解封您帳戶的決定，我們也不對您的帳戶負責。您選擇並考慮您的帳戶，並決定是否應該啟用所有功能，或者是否應該更加小心並謹慎行事。
