### ISSUE TITLE
Crashing Isuues

### ISSUE THREAD

**Issue by ENDERMANHEY** [CowNowK/AimStar#185]
Game randomly keeps crashing when aimstar is injected.

**Comment by ENDERMANHEY** [comment]
> > Game randomly keeps crashing when aimstar is injected.
> 
> Are you using any unsafe functions (ex. Smoke color, smoke removal, flashbang removal etc)?

Yes i am using smoke and flash removal while using the semirage config

**Comment by JannesBonk** [comment]
> > > Game randomly keeps crashing when aimstar is injected.
> > 
> > Are you using any unsafe functions (ex. Smoke color, smoke removal, flashbang removal etc)?
> 
> Yes i am using smoke and flash removal while using the semirage config

Try enabling safe mode, and check if you still crash.

**Comment by Nx0Ri** [comment]
Flash immunity and no smoke crashes sometimes

**Comment by JannesBonk** [comment]
> Flash immunity and no smoke crashes sometimes

every function/feature that writes to memory can crash the game

**Comment by ENDERMANHEY** [comment]
Disabling both seemed to fix it. Thanks yall!
