### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by dawidudek** [CowNowK/AimStar#186]
Hello
Do you know where in the source code there is a line for RAM usage? On devices with 8GB of memory (my friends testing this cheat), the cheat crashes. I don't have such a problem on a PC with 16GB of RAM. Could this be a problem?
Thank you in advance for any help

**Comment by JannesBonk** [comment]
> Hello
> Do you know where in the source code there is a line for RAM usage? On devices with 8GB of memory (my friends testing this cheat), the cheat crashes. I don't have such a problem on a PC with 16GB of RAM. Could this be a problem?
> Thank you in advance for any help

Are you both using the same config? Has he tried disabling unsafe functions? (ex. Flash immunity, No smoke, Smoke color etc.)

**Comment by dawidudek** [comment]
@JannesBonk I have disabled all dangerous functions (they are not on the cheat list) and safe mode is enabled by default (I removed the disable slider). The problem definitely lies in RAM. Me and my friend (we have 16gb) were the only ones who didn't experience game crashes.

**Comment by JannesBonk** [comment]
> @JannesBonk I have disabled all dangerous functions (they are not on the cheat list) and safe mode is enabled by default (I removed the disable slider). The problem definitely lies in RAM. Me and my friend (we have 16gb) were the only ones who didn't experience game crashes.

I did some testing on my old computer (I3 6006U, 8GB Ram DDR4 @ 2133mhz, Intel HD 520 graphics), and I experienced no issues. I am not 100% sure that "the problem definitely lies in RAM", as there are other factors that can make a cheat crash/close.

## Here are some recommendations I would suggest:
- Giving the software high priority (search that up if you don't know how)
- Check if the memory drastically increases (jumps from let's say 30mb to 70mb out of nowhere)
- Try using the official build from release if you haven't
- Try debugging the software (install Visual Studio, and launch using "Local Windows Debugger", and send a picture of the call stack here)

**Comment by M3351AN** [comment]
Aimstar may have a potential memory leak problem, but is not obvious rn. I think the issue is not due to RAM .I have tested aimstar on a 4Gb ddr3 device and it worked. cpu e3 1230v2& gpu r7 450 2g
