### ISSUE TITLE
[ERROR] Failed to update offsets. Press any key to continue . . .

### ISSUE THREAD

**Issue by bhawick25** [CowNowK/AimStar#188]
[ERROR] Failed to update offsets.
Press any key to continue . . .

**Comment by OvertimeDev-Random** [comment]
The update has been pushed to fix this issue

**Comment by rezox123** [comment]
[ERROR] Failed to update offsets.
Press any key to continue . . .

**Comment by 1vcbGH** [comment]
The error still continues even though they have modified the offsets

**Comment by M3351AN** [comment]
#187

**Comment by LewisLXTK123** [comment]
[autobuild [617f0ae76583c55016ffb722de5ce02c45db0c60]](https://github.com/CowNowK/AimStar/releases/tag/autobuild)
[ERROR] Failed to update offsets.
Press any key to continue . . .
