### ISSUE TITLE
您好，能帮我解决这个问题吗？关于自瞄Automatic aiming

### ISSUE THREAD

**Issue by 1thanks12** [CowNowK/AimStar#194]
您好，请问自瞄功能能恢复到4.0.3版本那个方式吗？就像旧自瞄一样按下自瞄键在范围内就直接锁定到敌人头顶上。因为新的自瞄方式锁定不到敌人，安全模式下自动锁定准心对准敌人后画面会到处飘，甚至瞄向天空，启用红锁会导致游戏崩溃退出。希望能出一个像以前一样按下自瞄按键后就锁定到敌人，而且平滑度很低能马上把准心对准到敌人，谢谢！
Hello, can the self aiming function be restored to version 4.0.3? Just like the old self aiming, pressing the self aiming button within range will directly lock onto the enemy's head. Due to the new self aiming method not being able to lock enemies, the screen will float everywhere and even aim towards the sky after automatically locking the focus in safe mode. Enabling the red lock will cause the game to crash and exit. I hope to create a self aiming button like before that can lock in the enemy immediately after pressing it, and the smoothness is very low, so that the focus can be immediately aligned with the enemy. Thank you!

**Comment by j621103** [comment]
我覺得還好
用了一陣子了
使用最新版的自瞄機器人沒問題
習慣了就好了

**Comment by 1thanks12** [comment]
> ###
> ** [j621103](/j621103) ** 已评论 [2024年3月3日](#issuecomment-1974887071) •

你好请问你是怎么设置的呢？锁定速度如何？能瞬间锁定到敌人头上吗？是否好用？
Hello, may I ask how you set it up? How fast is the locking speed? Can it instantly lock onto the enemy's head? Is it easy to use?

**Comment by CowNowK** [comment]
我没有这个问题，开启Aim Lock后就和旧版一样了

**Comment by 1thanks12** [comment]
> 对不起



> 我没有这个问题，开启Aim Lock后就和旧版一样了

您好作者，感谢您的辛苦付出。请问能否发布一个以前4.0.3版本一样的作弊器吗？只更新这个版本的更新偏移量，其他功能不变。因为这个版本是我用过最好用并且没有任何问题的一个版本。
Hello author, thank you for your hard work. May I ask if it is possible to release a cheat tool that is the same as version 4.0.3 before? Only update the update offset for this version, all other features remain unchanged. Because this version is the best one I have ever used without any issues.

**Comment by 1thanks12** [comment]
> 我没有这个问题，开启Aim Lock后就和旧版一样了
请问安全模式是不能关闭吗？因为现在只要关闭安全模式，开启自动锁定敌人和防止闪光游戏就会崩溃退出，开启安全模式自瞄和防止闪光等功能无效。
May I ask if the safety mode cannot be turned off? Because now as long as the safety mode is turned off, the automatic locking of enemies and preventing flash games will crash and exit, and functions such as self aiming and preventing flash in safety mode are ineffective.

**Comment by j621103** [comment]
我個人覺得
擁有者絞盡腦汁寫這個程式是免費的
並且固定時間更新
開放給大家使用
大家應該心存感激
既然是給大家使用的
尊重擁有者的創作自由
無法為個人量身訂做
還是請你體諒

I personally feel
The owner racked his brains to write this program for free
and updated at a fixed time
Open to everyone
Everyone should be grateful
Since it is for everyone to use
Respect the creative freedom of the owner
Cannot be customized for individuals
Please forgive me

**Comment by 1thanks12** [comment]
> 我个人觉得 所有者绞尽脑汁写这个程序是免费的 并且固定时间更新 开放给大家使用 大家应该心存感激 既然是给大家使用的 尊重所有者的创作自由 无法为个人量身订做 还是请你体谅
> 
> 我个人觉得 老板绞尽脑汁免费编写这个程序，并在固定时间更新 向所有人开放 每个人都应该心存感激 既然是给大家使用的 尊重老板的创作自由 不能为个人定制 请见谅

您好，首先感谢您的回答。其次，我没有在任何言语中表达我觉得这是个理所当然的事，并且我首先对作者的感谢与辛苦，并无你说的没有感激。而且我也没有不尊重作者的意愿，也没有表达作者必须为我个人而创作使用，没有进行道德绑架，我只是询问和希望获取帮助。请不要因为您的主观意识，导致大家客观理解错误或者引起破坏和谐的关系。
Hello, first of all, thank you for your answer. Secondly, I did not express in any words that I felt it was a matter of course, and first of all, I am grateful to the author for their hard work, as you said. And I also did not disrespect the author's wishes, nor did I express that the author must create and use it for my personal benefit, nor did I engage in moral coercion. I only asked and hoped for help. Please do not let your subjective consciousness lead to objective misunderstandings or disrupt harmonious relationships.

**Comment by M3351AN** [comment]
没有必要为此争执，提出意见是好的，不过值得一提的是，当前版本的瞄准机器人和4.0.3版本的最大区别是start bullet和min fov，一般来讲在设置min fov和start bullet为0的情况下aimbot的工作方式与4.0.3版本应该没有差异
reporting issue is fine ,we do not need to argue. btw the only difference between latest version aimbot and v4.0.3 is the min fov and start bullet. as you change these two to minimum values, theoretically, aimbot should work like v4.0.3

**Comment by 1thanks12** [comment]
> 没有必要为此争执，提出意见是好的，不过值得一提的是，当前版本的瞄准机器人和4.0.3版本的最大区别是start bullet和min fov，一般来讲在设置min fov和start bullet为0的情况下aimbot的工作方式与4.0.3版本应该没有差异 reporting issue is fine ,we do not need to argue. btw the only difference between latest version aimbot and v4.0.3 is the min fov and start bullet. as you change these two to minimum values, theoretically, aimbot should work like v4.0.3


Thank you for your answer. I'm sorry that the updated self aiming function has indeed caused me a headache. I have been studying for a long time but haven't been able to debug to the same feeling. Maybe I made it complicated, or maybe I don't know how to use it anymore. I don't know if the red lock function inside can be turned on or not. It seems that even the self aiming violence function will fail in safe mode, such as anti flashing and self aiming floating everywhere. My feeling is that the self aiming function is not as useful as before, but it may also be due to my own feelings, which does not negate your efforts and success, as well as the free happiness you bring us. thanks
感谢您的回答，抱歉更新之后的自瞄功能的确让我头疼。我研究了很长时间都没有调试到一样的感觉。也许是我搞复杂了，或者是我不会使用了。里面的红锁功能我也不知道到底能不能开，好像安全模式下自瞄暴力功能都会失效，比如防闪光，自瞄也会到处飘。我的感觉就是自瞄功能没有之前那么好用，当然也有可能是自我感觉，并不否定你们的付出和成功，以及带给我们免费的快乐。谢谢

**Comment by j621103** [comment]
(過來人的經驗)
1.安全模式還是開著比較好
不然會被 VAC ban
我就是安全模式都關掉
開啟比較進階的功能
玩一段時間之後
被 VAC ban

2.安全模式中,防閃光開啟
測試結果無作用
眼睛被閃瞎掉

(Experience of people who have been there)
1. It is better to leave the safe mode on
Otherwise you will be banned by VAC
I just turned off safe mode
Enable more advanced features
After playing for a while
Banned by VAC

2. In safe mode, anti-flash is turned on
Test results have no effect
Eyes were blinded by flashes

**Comment by CowNowK** [comment]
@j621103 
> 2.安全模式中,防閃光開啟 測試結果無作用 眼睛被閃瞎掉

目前已知蓝宝石换肤器会导致部分功能失效
