### ISSUE TITLE
Autowall

### ISSUE THREAD

**Issue by qw1dixx** [CowNowK/AimStar#199]
https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
add in 4.3.3 pls

**Comment by JannesBonk** [comment]
> https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
> add in 4.3.3 pls

Autowall will take alot of resources just to see if it can hit 1 player. It's better to do it internally than externally, as it's not only faster, but more accurate.

**Comment by JannesBonk** [comment]
> https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
> add in 4.3.3 pls

If you are looking for a good autowall method, I recommend doing BSP parsing.

**Comment by M3351AN** [comment]
> > https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
> > add in 4.3.3 pls
> 
> If you are looking for a good autowall method externally, I recommend doing BSP parsing.

However bsp parsing method doesn't work on cs2 since valve packed map files into vpk files , and u have to unpack it before parsing

**Comment by JannesBonk** [comment]
> > > https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
> > > add in 4.3.3 pls
> > 
> > If you are looking for a good autowall method externally, I recommend doing BSP parsing.
> 
> However bsp parsing method doesn't work on cs2 since valve packed map files into vpk files , and u have to unpack it before parsing 

It's still possible

**Comment by M3351AN** [comment]
> > > > https://www.unknowncheats.me/forum/counter-strike-2-a/577668-autowall.html
> > > > add in 4.3.3 pls
> > > 
> > > 
> > > If you are looking for a good autowall method externally, I recommend doing BSP parsing.
> > 
> > 
> > However bsp parsing method doesn't work on cs2 since valve packed map files into vpk files , and u have to unpack it before parsing
> 
> It's still possible

but very very complex

**Comment by pogrammerX** [comment]
AFAIK map files have always been VPK files... just checked even in HL2 and portal 2 its all packed in VPKs, so I doubt there will be any difference...
