### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by hell99dkx** [CowNowK/AimStar#207]
![image](https://github.com/CowNowK/AimStar/assets/132538402/63bdec2f-c4d8-4c0e-84a8-90c50bd94c6c)
As shown in the figure, I attempted to clone the source code of the project and compile it on VS2022, but encountered a large number of errors. If you could provide me with a solution, I would be extremely grateful

**Comment by M3351AN** [comment]
通常是由于项目属性的设置引起的
usually due to project prop settings
