### ISSUE TITLE
[ERROR] Falied to update offsets 

### ISSUE THREAD

**Issue by 1vcbGH** [CowNowK/AimStar#208]

**Comment by danoo-C** [comment]
yes, its because of the new cs2 update, hope dev fixes soon.

**Comment by 1vcbGH** [comment]
thanks bro

**Comment by pogrammerX** [comment]
Should be fixed now, they updated the offsets @1vcbGH

**Comment by 1vcbGH** [comment]
> Should be fixed now, they updated the offsets @1vcbGH

ty bro

**Comment by borko299** [comment]
dosen't work, I try
