### ISSUE TITLE
[ERROR] Weird looking ESP

### ISSUE THREAD

**Issue by 4345dgfsd** [CowNowK/AimStar#209]
Hiya, from version 4.3.3 to latest, i've got a weird bug which is very disorienting. When i move my camera, the ESP moves with the camera aswell, then locks back onto the person which looks very weird and it's even more difficult to use ESP properly, any fix for this?

4.3.2 ESP worked like a charm

If i have to i can show more information such as video.. etc...

Thanks.

**Comment by pogrammerX** [comment]
It would help if you could provide a video or screenshot

**Comment by 4345dgfsd** [comment]
Hi, sorry for the bad quality, hopefully you can see what i am talking about.

https://www.dropbox.com/scl/fi/meavrlfwqmhfpluot6dzo/vid.mp4?rlkey=61rvhflg6cq4ookq24uuxtqnt&dl=0

**Comment by pogrammerX** [comment]
I don’t see what’s wrong with it?

4345dgfsd ***@***.***> schrieb am Fr. 15. März 2024 um 19:30:

**Comment by 4345dgfsd** [comment]
Do you see how the esp moves along when i move my mouse aswell? in 4.3.2 that issue did not exist, and the esp was locked onto the enemy player. While in newer versions, the esp "delays" and then locks back onto the enemy player..

**Comment by pogrammerX** [comment]
That's normal, external ESPs will always have delay

**Comment by 4345dgfsd** [comment]
Okay, thank you very much. 👍
