### ISSUE TITLE
RCS jerking bug

### ISSUE THREAD

**Issue by Mega-Dev-Eloper** [CowNowK/AimStar#210]
Sometimes, after releasing the LMB, the crosshair jerks sharply to the bottom of the screen. This became especially pronounced after 4.3.3 and later. Previously, this problem also occurred, but it happened less often. I tried to fix it myself, but the code is too confusing. Thanks for any help.

Video: https://gofile.io/d/KCh8Pz

**Comment by blondedye** [comment]
same problem, i tried fixing the rcs code multiple times but i can’t really work with it

**Comment by CowNowK** [comment]
Fixed in lastest
