### ISSUE TITLE
[ERROR] Failed to update offsets

### ISSUE THREAD

**Issue by LuckyMan612** [CowNowK/AimStar#211]
![image](https://github.com/CowNowK/AimStar/assets/75744132/105dccc1-164c-4110-8cb1-0117c5bfa50c)

**Comment by VVoiddd** [comment]
it works fine for me if you got 4.3.4
![image](https://github.com/CowNowK/AimStar/assets/143309999/93f098c4-bb5a-4919-b029-48fadbc6bf42)

**Comment by CowNowK** [comment]
use 4.3.4+

**Comment by Lanslow4** [comment]
mine just says cant find offsets.yaml

**Comment by vojtano2950** [comment]
> mine just says cant find offsets.yaml

do you know how to repair?
