### ISSUE TITLE
Failed to update offsets

### ISSUE THREAD

**Issue by LuckyMan612** [CowNowK/AimStar#214]
![image](https://github.com/CowNowK/AimStar/assets/75744132/244ab3d5-415e-4121-a1c3-2863d74526d5)

**Comment by VVoiddd** [comment]
use 4.3.4 with admin perms 


![image](https://github.com/CowNowK/AimStar/assets/143309999/7985b9d0-952d-444c-8eda-69ce45b9ea07)
