### ISSUE TITLE
Who will buy Aimware and Gamesense and NeverLose

### ISSUE THREAD

**Issue by 3-commerce** [CowNowK/AimStar#215]
This is real issue among other issues here.

Main issue, if this AimStar project continue and well maintained then who will buy Aimware and Gamesense and NeverLose ?

This project instantly kills NN CS2 cheats and only 3 kings Aimware and Gamesense and NeverLose are still strong.

That's the issue. I just reviewed this cheat and surprised this well maintained. I am affraid the big cheats providers will dead LMAO

**Comment by M3351AN** [comment]
btw, i suspect this project is likely to be the base of many nn cheats. afaik even some internal bases have copied some functions from aimstar/tkazer to reduce workload
