### ISSUE TITLE
[NOTICE] Flagged for ban wave

### ISSUE THREAD

**Issue by vnodeDYNAMIC** [CowNowK/AimStar#217]
Inside source revealed some of the external features used in TKazer's CS2_External have been flagged by Valve and are to be detected after the next ban wave scheduled for April 5th - after the Conpenhagen Major. I recommend not using the features until the ban wave hits so it can be determined which features are and aren't flagged, unless getting banned doesn't bother you (whoever is reading this). I don't have any information on how long the flagging first took place but probably accounts that used some of the features weeks or months ago until april might be hit with the ban wave. Good run anyways, open source is always a risk but it is also the best for learning.

![CNDI_204890820890389409](https://github.com/CowNowK/AimStar/assets/164053010/4f16784c-f97c-4aa0-a5e4-3ba42ab1df66)

**Comment by darken-san** [comment]
It might be hoax, the way you say it is very inconsistent, your source said that it is confirmed but he says "probably" it will take after the April 5th with an unsure face, also you just said that they already flagged and detected some features "only", it doesn't make any sense for Valve to detect those said features alone after all the cheat source code is "public" and it should detect everything on it, afaik. they only do manual banning as for now, if the cheat features were detected by Valve at short notice, Valve will immediately banned the users between 24-48 hrs. prior to the infraction, also I checked the recent trends of VAC banned players, I only see 5-10 ppl. that got hit, there is no such thing as super delayed ban unless we are talking about the old era of CS. They do VAC ban ppl. regularly, as you can see in the trend [https://convars.com/csgostats/en/bans], this site is accurate, there is no such thing as "ban-waves" it is just a fancy name for cheat got detected and the users who injected the cheat prior to the detection are the only ones who will get hit by it, provide a proper source that isn't just a "random" discord user.

**Comment by vnodeDYNAMIC** [comment]
Maybe I didn't express it correctly: it's confirmed it has been flagged, not that the ban wave will be on april 5th, could be earlier or after, but most probably in april after the majors because a major update to CS2 is coming around that same time, scheduled for april 5th. AC devs don't patch every vulnerability they encounter in a public source code because that's not how progamming works, it takes time to patch every possible vulnerability that does not require the code to be rewritten from scratch nor to break any other functions in the code that could break the game in some aspect, etc., this is why rapid fire still hasn't been patched despite the developers knowing it is being used for cheating, because fixing it would require to rewrite most of the code, this is also the reason why ban waves are delayed, because they are not pushing the update with these new fixed vulnerabilities in the middle of a major championship in fear of messing up game features or aspects, which has happened before.

Valve is not performing manual bans on CS2 since OW was terminated, they rely completely on VACNET and VACLive, manual bans are now very rare ocurrences, it's not new that Valve flags cheat features to later on perform a ban wave, in fact it's been how most ban waves happen since the release of CS2. All other bans are not manual, they get detected by VACLive or VACNET mostly due to bad injectors of internal cheats or crap VAC bypass, raging features that aren't safe, etc. And like I said, I don't know nor was I told if the ban wave will hit only people who use the cheat after the update or if they flagged some internal specific signatures for this cheat in order for the ban to also have an effect on accounts that used the detected features prior to the update, although this has happened before in the same way as the last ban wave of AimWare where people got banned without using the cheat after the update, they were flagged prior to the ban wave, and this has happened before with other cheat features too.

As per my source, for obvious reasons I am not going to disclose any information nor provide further proof. It's up to you if you want to believe it or not, I honestly don't care, the point of this issue was just to alert the developers to keep an eye open during the next following weeks so they can be prepared to analyze what got detected and what didn't, it's a project I respect in regards to code programming, not its users nor their concerns of being banned, and I guess that in a way it also serves to alert whoever uses this cheat on their main account (which is a quite literally dumb decision).

So keep your fears to yourself and just wait. Either way this issue isn't meant for you, it's for the developers.

**Comment by darken-san** [comment]
Why he only mentions T_Kazer source?? What about the other free open source cheats like Osiris and other free open sources CS2 cheats??? It seems inconsistent and like I said why is he talking with an unsure face, always saying "probably" and also why can't you provide an evidence?? Are you hiding the facts, it is just a hoax full of "probably" imagine you claimed it is flagged but can't present proof, I think you're just talking to a random troll, it is just stupid for Valve to accidentally exposed or leak their own banwave pattern.

**Comment by Mirkaanks** [comment]
Among the different applications I made, I noticed that detection is more about the means used than what uses.

**Comment by 3-commerce** [comment]
https://github.com/CowNowK/AimStar/blob/main/CS2_External/Offsets.h#L159-L174

That part, please avoid scanning memory. CS2 will update VAC engine 2 April or 9 April.

Scanning memory method leads permanently untrusted after that update.

Good Luck

**Comment by snkfranco** [comment]
Sheeeshhhh

**Comment by darken-san** [comment]
Where's the ban wave? that you're talking?? CS2 just updated and nobody got banned don't tell me the next flagging ban wave is scheduled to May 5th lfmao.

**Comment by darken-san** [comment]
Where's the ban wave? that you're talking?? CS2 just got updated and nobody got banned don't tell me the next flagging ban wave is scheduled to May 5th??
