### ISSUE TITLE
开启Aimbot功能之后 RCS功能就会失效

### ISSUE THREAD

**Issue by smilepeak** [CowNowK/AimStar#219]
开启Aimbot功能之后 RCS功能就会失效

After activating the Aimbot function, the RCS function will become invalid

**Comment by Mirkaanks** [comment]
test my pr #220

**Comment by Jeroonymo** [comment]
Same here, with the latest app when I activate both functions, the RCS doesn't work

**Comment by CowNowK** [comment]
如果你开启了自瞄，那么rcs的工作模式会切换到自瞄运行时才会压枪，如果自瞄没有在运行，那么rcs就不会压枪
