### ISSUE TITLE
keep shuting down

### ISSUE THREAD

**Issue by rauljoseph85** [CowNowK/AimStar#223]
aimstar keep shut down. while in the game

**Comment by rauljoseph85** [comment]
cmd file still run, but app stop showing up when press INSERT

**Comment by CapDezzy** [comment]
having the same problem

**Comment by CapDezzy** [comment]
Name der fehlerhaften Anwendung: AimStar.exe, Version: 1.0.0.0, Zeitstempel: 0x65eb5032
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.22621.2506, Zeitstempel: 0x097c794c
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000000000007f61e
ID des fehlerhaften Prozesses: 0x0x970
Startzeit der fehlerhaften Anwendung: 0x0x1DA7BA7B6F04E8B
Pfad der fehlerhaften Anwendung: C:\Users\jekas\Downloads\AimStar_4.3.3\AimStar.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\ucrtbase.dll
Berichtskennung: b25f4c93-c5aa-4349-8a32-eb18a892edab
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

In archived problems found this

**Comment by Mirkaanks** [comment]
Probably is your graphic settings. Could you tell me which methods you use, and which video card?

**Comment by CapDezzy** [comment]
> Probably is your graphic settings. Could you tell me which methods you use, and which video card?

I am using in a Laptop, a 3050 Nvidia with an I5 intel and what do you mean with "graphic settings" does it crash thats why or how?

**Comment by CowNowK** [comment]
What is your Windows version? This may be a system problem

**Comment by CapDezzy** [comment]
Windows 11

**Comment by unofficialdxnny** [comment]
you need to be in window fullscreen + if the game keeps closing its because the aimbot or other hacks are obvious
so lmk and i will give you my config.

**Comment by jdnndcj** [comment]
什么垃圾东西一直掉

**Comment by Wuemeli** [comment]
Still a Problem?

**Comment by psxjtwr01** [comment]
> Still a Problem?

yea i have an issue where esp half works and crashes game

**Comment by Wuemeli** [comment]
> > Still a Problem?
> 
> yea i have an issue where esp half works and crashes game

Did you try latest Autobuild/Release? Are you in Windowed Mode? Antivirus Disabled?
