### ISSUE TITLE
aimstar is detected as a virus and keeps shuting down. 

### ISSUE THREAD

**Issue by BoredIT1** [CowNowK/AimStar#225]
Currently, there seems to be an issue with Aimstar not opening when the real-time protection feature is enabled in Windows Defender. I've tested it across different versions of Aimstar, but never encountered this problem before. Additionally, even when you disable the real-time protection, Aimstar opens briefly but then shuts down after about 10 seconds. This behavior is also something I haven't experienced with other versions of Aimstar.

**Comment by M3351AN** [comment]
This is normal. Aimstar, as a cheat, executes process such as listening keystate, handle hijacking, and write process memory, which are "dangerous" for ordinary software.
You can add aimstar to your av software whitelist, or temporarily close av software
For me, my Kaspersky did not detect aimstar as a virus
I strongly recommend to disable Windows defender and use other av software
