### ISSUE TITLE
dosnt work on two monitors esp aimbot dont work

### ISSUE THREAD

**Issue by Germanized** [CowNowK/AimStar#229]
doesn't work on two monitors esp aimbot don't work and only able to be opened if I click the the application on my taskbar and click INS

**Comment by Germanized** [comment]
like i have to click on it in taskbar then click ins then it shows up but when i tab back into game it disappears and the visuals wont work with it and this started happening when i got a second monitor and i unplugged it restarted and it still did it

**Comment by PhillipThePaster** [comment]
> like i have to click on it in taskbar then click ins then it shows up but when i tab back into game it disappears and the visuals wont work with it and this started happening when i got a second monitor and i unplugged it restarted and it still did it

are you in fullscreen

**Comment by Germanized** [comment]
No fullscreen windowed

**Comment by Germanized** [comment]
> > like i have to click on it in taskbar then click ins then it shows up but when i tab back into game it disappears and the visuals wont work with it and this started happening when i got a second monitor and i unplugged it restarted and it still did it
> 
> 
> 
> are you in fullscreen

No I'm in full screen windowed

**Comment by PhillipThePaster** [comment]
> > > like i have to click on it in taskbar then click ins then it shows up but when i tab back into game it disappears and the visuals wont work with it and this started happening when i got a second monitor and i unplugged it restarted and it still did it
> > 
> > 
> > are you in fullscreen
> 
> No I'm in full screen windowed

join the discord and put your issue in there

**Comment by CowNowK** [comment]
It worked on my pc with 3 monitor
