### ISSUE TITLE
[suggestion] fov changer

### ISSUE THREAD

**Issue by rdmxboy** [CowNowK/AimStar#230]
please add an ingame fov changer

**Comment by rdmxboy** [comment]
oh sorry nvm

**Comment by rdmxboy** [comment]
wait but the fov changer doesnt change the viewmodel fov

**Comment by OWnlyx** [comment]
> wait but the fov changer doesnt change the viewmodel fov, please make it change viewmodel too

you just could use the cs2 command to change ur viewmodel
viewmodel_fov 68.000000
viewmodel_offset_x 1.000000
viewmodel_offset_y 1.000000
viewmodel_offset_z 1.000000
