### ISSUE TITLE
After using AimStar, the frame delay has increased to 200ms, causing severe lag.

### ISSUE THREAD

**Issue by ALEXMETR** [CowNowK/AimStar#231]
In version 4.3.6, without injecting AimStar, the frame delay can remain in single digits. However, after injection, the frame delay increases to over 200ms.

**Comment by DokiOnLowest** [comment]
> In version 4.3.6, without injecting AimStar, the frame delay can remain in single digits. However, after injection, the frame delay increases to over 200ms.

AimStar is external not internal
