### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MAX1MDEV** [CowNowK/AimStar#238]
Crashes the game when I get killed or when switching sides

**Comment by CowNowK** [comment]
how did u know it is Aimstar crashed ur game

**Comment by MAX1MDEV** [comment]
> how did u know it is Aimstar crashed ur game

because with another midnight cheat or without cheats at all, everything is fine and there are no crashes.

**Comment by CowNowK** [comment]
if u injected other internal cheat at the same time, AimStar might crash your game, just stop using memory features

**Comment by MAX1MDEV** [comment]
Im inject only aimstar
