### ISSUE TITLE
4.3.8

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#242]
shot Delay
shot Duration 
doesn't work

**Comment by ByteCorum** [comment]
Thx, for your feedback. It gonna be fixed asap.

**Comment by ByteCorum** [comment]
As I can see only shot delay doesn't work

**Comment by ByteCorum** [comment]
@CowNowK, this issue can be closed

**Comment by CowNowK** [comment]
Should be fixed in new version
