### ISSUE TITLE
我该如何编译这个程序

### ISSUE THREAD

**Issue by NeverloseMLN** [CowNowK/AimStar#243]
![微信截图_20240407151117](https://github.com/CowNowK/AimStar/assets/98944302/027fe0f3-0ade-426b-b3ee-424179d23a8f)
直接编译会显示这个

**Comment by NeverloseMLN** [comment]
VS2022
![微信截图_20240407151213](https://github.com/CowNowK/AimStar/assets/98944302/579d4c73-26a7-4836-8b38-b4ecbc7fc63d)

**Comment by ByteCorum** [comment]
https://github.com/microsoft/terminal/issues/483

**Comment by ByteCorum** [comment]
https://developercommunity.visualstudio.com/t/2019-fatal-error-c1083-cannot-open-include-file-at/518592

**Comment by ByteCorum** [comment]
It should help

**Comment by CowNowK** [comment]
安装atl扩展库
