### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by unofficialdxnny** [CowNowK/AimStar#259]
I loaded up cs2 with bots but the game keeps crashing with this running. I dont know why? i just wanted to test it out with the bots haha.

**Comment by unofficialdxnny** [comment]
keep getting error no steam logon?

**Comment by ENDERMANHEY** [comment]
> Brother it's a trojan my guy.

Brother it's open source my guy.

**Comment by ENDERMANHEY** [comment]
> keep getting error no steam logon?

verify file integrity

**Comment by psxjtwr01** [comment]
ive personally gone thru all the source code and being a dev its just ass source but no viruses to be found :)

**Comment by M3351AN** [comment]
> ENDERMANHEY it beign open-source doens't mean it's not malware. I've analyzed the code for my Uni's assignment (yes the assigment was to find and analyze code from github, and determine if it has malware, so I went to cheat's since most of them do). And with a group we found 7 viruses one of them being a trojan :(

imagine a guy never watch the code and found 7 viruses via virustotal
go learncpp.com
and try found which line of the code is "virus"

otherwise stfu n go over your kindgarden homework
