### ISSUE TITLE
Crashes the game when I get killed or when switching sides

### ISSUE THREAD

**Issue by MAX1MDEV** [CowNowK/AimStar#261]
Namely, this is what happens when I turn on the “No smoke” function. Im inject only aimstar.

**Comment by primewk** [comment]
No smoke dosnt work and crashes. COZ COW IS A DUMB CHINESE PASTER

**Comment by M3351AN** [comment]
> No smoke dosnt work and crashes. COZ COW IS A DUMB CHINESE PASTER

The issue is very simple. As an experiment we have no intention of maintaining this buggy function. The next version will remove this switch, so that you can try paste by urslf

**Comment by MAX1MDEV** [comment]
> > No smoke dosnt work and crashes. COZ COW IS A DUMB CHINESE PASTER
> 
> The issue is very simple. As an experiment we have no intention of maintaining this buggy function. The next version will remove this switch, so that you can try paste a non-gook code by urslf

dont worry, this boy is dumb
