### ISSUE TITLE
can you make just glow esp

### ISSUE THREAD

**Issue by Kasaravcisi79** [CowNowK/AimStar#262]
i need just glow can you make this i play legit and i play 4:3 streched i dont want any feature just glow esp

**Comment by psxjtwr01** [comment]
its been in the cheat for a while

**Comment by M3351AN** [comment]
> i need just glow can you make this i play legit and i play 4:3 streched i dont want any feature just glow esp

m_flDetectedByEnemySensorTime is removed by valve

**Comment by DrexWare** [comment]
> > i need just glow can you make this i play legit and i play 4:3 streched i dont want any feature just glow esp
> 
> m_flDetectedByEnemySensorTime is removed by valve

No it isnt??? I have been using in my externals and internals over the past week
