### ISSUE TITLE
Aimbot Trigger Not Working and Spinning when Firing After Latest CS2 Update

### ISSUE THREAD

**Issue by vivabonito** [CowNowK/AimStar#268]
Latest CS2 update broke Aimstar. Now, aimbot trigger key does not work, and player spins when fire key (left mouse button) is pressed. I believe the latest update made changes to the offset, hence causing these issues.

**Comment by heiole** [comment]
I've got the same issue. Also a few small things I noticed is: 
1. The camera is rotating when you are firing from an automatic weapon.
2. The armor bar is infinitely high, it literally touches the sky (pink bar)
![image](https://github.com/CowNowK/AimStar/assets/122667196/41fcedff-6197-497d-9448-7ff42eda94c8)

**Comment by 6KKK6** [comment]
I thought I was the only one!

**Comment by xpired2k** [comment]
When trigger is gonna work?

**Comment by heiole** [comment]
Just tested the latest autobuild. 
Great news: The camera does not spin, and the armor bar glitch got fixed.
Bad news: The aimbot does not work, at all.

**Comment by heiole** [comment]
the aim does not work. every other glitch has been fixed.

**Comment by xpired2k** [comment]
WORKS

**Comment by Plejejs** [comment]
Now the only problem is aim lock all the time

**Comment by remydeleeuw** [comment]
aim lock isn't working anymore since last cs update

**Comment by heiole** [comment]
@M3351AN So, I was testing those autobuilds. As of now, cheats work great! I guess you can close this topic. And also release the latest autobuild. I even feel that the aimbot works better.

**Comment by Asad7268** [comment]
@heiole can you explain me how to use autobuild plzzzzzz

**Comment by Wuemeli** [comment]
I think it can be closed
