### ISSUE TITLE
[ping issue when cheat is on]

### ISSUE THREAD

**Issue by khayyamov** [CowNowK/AimStar#272]
When I use this cheat(AIMBOT), my ping goes from 40 to 200 in the second round, but when I stop the cheat and play, my ping is 40 again until the end.

**Comment by xpired2k** [comment]
trigger not working propetly

**Comment by khayyamov** [comment]
it working int.h updated xD https://github.com/CowNowK/AimStar/actions/runs/8818732971/artifacts/1443702616
