### ISSUE TITLE
New CS2 Update Broke the Cheat...Again!

### ISSUE THREAD

**Issue by huntd3v** [CowNowK/AimStar#274]
The 4/25 update to CS2 which includes addition of Overwatch (be careful how blatant you are!) rendered every cheat function past the menu and fps counter non-functional. no aim, no rec, no esp, nothing works as of now.

**Comment by ENDERMANHEY** [comment]
huh seems like valve is doing something

**Comment by huntd3v** [comment]
possibly, im trying to figure out how to update it to work with new cs2 upd but not 100% sure what im doing

**Comment by boyo3473** [comment]
> The 4/25 update to CS2 which includes addition of Overwatch (be careful how blatant you are!) rendered every cheat function past the menu and fps counter non-functional. no aim, no rec, no esp, nothing works as of now.

you just need to update the offsets

**Comment by Filipes420** [comment]
how to update offsets?

**Comment by Wuemeli** [comment]
Try newest Autobuild

**Comment by Wuemeli** [comment]
Can be closed i think
