### ISSUE TITLE
autobuild [ca6d4d

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#279]
No effect

**Comment by Wuemeli** [comment]
What do you mean?

**Comment by Wuemeli** [comment]
@j621103

**Comment by j621103** [comment]
skeleton
Reflective
Robot automatic aiming
All invalid
If you don’t believe me, give it a try

**Comment by CowNowK** [comment]
4.4.1 is working well
Nothing changed from last [update](https://github.com/a2x/cs2-dumper/commit/b0218519b50d7e80ac37b8c3f6a1ee47cabe9013#diff-40dd0e2c6846f338f6407ea1b7795bd3ab90aa9f788e9793c09c10e6a52e4e78)

**Comment by M3351AN** [comment]
now it should be working
![Screenshot_2024-04-27-22-05-13-835_net xrcloud](https://github.com/CowNowK/AimStar/assets/65479796/e82c3955-bc93-464a-9dcd-4d7851b4a66e)
