### ISSUE TITLE
Auto build doesn’t work

### ISSUE THREAD

**Issue by Zenx21** [CowNowK/AimStar#281]
Only some parts of the latest auto build seem to work like the bunny hop, other than that the esp, aimbot, triggerbot don’t work.

**Comment by Wuemeli** [comment]
The offsets need to be updated, we need to wait. And I'm too lazy to do it

**Comment by Wuemeli** [comment]
Just wait until next Update

**Comment by M3351AN** [comment]
now it should be working
![Screenshot_2024-04-27-22-05-13-835_net xrcloud](https://github.com/CowNowK/AimStar/assets/65479796/e82c3955-bc93-464a-9dcd-4d7851b4a66e)
