### ISSUE TITLE
when i run aimstar it closes instantly and when i try and se debug by using cmd this is what it showes how do i fix it??

### ISSUE THREAD

**Issue by AceNo7a** [CowNowK/AimStar#282]
when i run aimstar it closes instantly and when i try and se debug by using cmd this is what it showes how do i fix it??
![image](https://github.com/CowNowK/AimStar/assets/168284214/78b897cb-53f2-4f9b-859e-9ba06795061e)

**Comment by M3351AN** [comment]
It looks like aimstar successfully obtained the game's pid and memory address, but was perhaps blocked from running further by the antivirus (handle hijacking was blocked) Try to check antivirus records and add aimstar to the whitelist

**Comment by AceNo7a** [comment]
> It looks like aimstar successfully obtained the game's pid and memory address, but was perhaps blocked from running further by the antivirus (handle hijacking was blocked) Try to check antivirus records and add aimstar to the whitelist

i have antivirus disabled and i have added it to exclusions and as far as i know i got no other antivirus. I have also installed cpp runtimes.

**Comment by Wuemeli** [comment]
Try the latest autobuild

**Comment by CowNowK** [comment]
did you installed c++ runtime?

**Comment by AceNo7a** [comment]
> Have you installed c++ runtime?

I have mentioned above that I have but it's fine. I'll say it again, I have installed all cpp runtimes.

> Try the latest autobuild

I have also tried using latest autobuiold

**Comment by AceNo7a** [comment]
It work with windows 11 though correct?

**Comment by AceNo7a** [comment]
I also am running the game on Fullscreen Windowed

**Comment by AceNo7a** [comment]
quick little update, i had some tweaks installed using the ChrisTitusTech tweaker mod menu and after disabling them it seems that the terminal stays open for a little longer and then closes with an extra two lines of error or so. when i tried to run in cmd to see what the error is at the end it just wouldn't show anything.

**Comment by AceNo7a** [comment]
I have just installed visual studio 2022 and now when i run  the aimstar it shows me this 
![image](https://github.com/CowNowK/AimStar/assets/168284214/f3ac81a1-0e1f-4d9a-b19a-fbccff01a04e)

**Comment by AceNo7a** [comment]
I have just uninstalled vs community and now i get this error when i run the application

![image](https://github.com/CowNowK/AimStar/assets/168284214/9b39f859-7ac0-444c-adef-6041f23cd5c0)

**Comment by Wuemeli** [comment]
Did you disable Antivirus? Tryed the latest Autobuild?

**Comment by AceNo7a** [comment]
I have disabled it and it still didn't work, but I have reset the PC and
now it works I didn't even install cpp runtimes as of now on the reset😐
