### ISSUE TITLE
[ERROR] Failed to get module address.

### ISSUE THREAD

**Issue by BohdanSylich** [CowNowK/AimStar#287]
![Знімок екрана 2024-04-28 133021](https://github.com/CowNowK/AimStar/assets/121378619/a13a41d4-58a7-4995-ab39-6dbf22a07dbd)

**Comment by joempacn** [comment]
Thank you for the development of Aimstar. However I am having the same issue on my end. Can't load offsets.
I am using Windows 11 26100.268

Hoping for the fix. Thank you!

**Comment by Wuemeli** [comment]
Did you disable Antivirus? Tryed the latest Autobuild?

**Comment by joempacn** [comment]
I have disabled the antivirus and ran the 4.3.8 version.

**Comment by M3351AN** [comment]
> I have disabled the antivirus and ran the 4.3.8 version.

4.3.8 is out dated

**Comment by joempacn** [comment]
Tried with commit da9f67934ce8c3cea8d623fd9c70af3f1a8c88e0.

Disabled antivirus.
Ran as administrator.
CS2 process is running.

Still the same issue.

![image](https://github.com/CowNowK/AimStar/assets/150117048/8d897975-5671-473b-9359-30719e3ef238)

**Comment by CowNowK** [comment]
> Tried the build artifact in commit da9f67934ce8c3cea8d623fd9c70af3f1a8c88e0.
> 
> Disabled antivirus.
> Ran as administrator.
> CS2 process is running.
> 
> Still the same issue.
debug it
