### ISSUE TITLE
Failed to update offsets

### ISSUE THREAD

**Issue by joempacn** [CowNowK/AimStar#290]
![image](https://github.com/CowNowK/AimStar/assets/150117048/62c6e42b-0639-426c-9638-508572c8a4af)

Issue on 
Using latest May 1 Build
Windows 11 26100.268
Run as admin
Disabled antivirus
CS2 is running

**Comment by j621103** [comment]
win 10
Execute normally

**Comment by M3351AN** [comment]
> ![image](https://private-user-images.githubusercontent.com/150117048/327049961-62c6e42b-0639-426c-9638-508572c8a4af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTc0MTgsIm5iZiI6MTcxNDU1NzExOCwicGF0aCI6Ii8xNTAxMTcwNDgvMzI3MDQ5OTYxLTYyYzZlNDJiLTA2MzktNDI2Yy05NjM4LTUwODU3MmM4YTRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQwOTUxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDhmOWJmMzdiMGUwOWJkNDNiYjUxMjgwNTVmNGI3YjE3ZmU5MjIzMWIxOTM4ZWM1NTE4ZTM2YzI5NWI2NjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xn13h3RSJdz878n_gVEsKLiX_H7qDnL015FHRvx0fuc)
> 
> Issue on Using latest May 1 Build Windows 11 26100.268 Run as admin Disabled antivirus CS2 is running

Obviously this is not the latest build in this screen shot
