### ISSUE TITLE
Failed to Update Offsets on May 1 Build

### ISSUE THREAD

**Issue by joempacn** [CowNowK/AimStar#291]
![image](https://github.com/CowNowK/AimStar/assets/150117048/1ce99028-0779-4b12-8db4-32e75daaf20a)

Issue on
Using latest May 1 Build
Windows 11 26100.268
Steam client 1709846872
Run as admin
Disabled antivirus
CS2 is running

TempAddressList is always 0 when calling SearchMemory
`TempAddressList = ProcessMgr.SearchMemory(Signature, ModuleAddress, ModuleAddress + 0x4000000);`

**Comment by joempacn** [comment]
How to view runtime logs so that I can also check the issue?

**Comment by Sigma12456** [comment]
update offsets
