### ISSUE TITLE
error when executing

### ISSUE THREAD

**Issue by JoaozimBr2016** [CowNowK/AimStar#292]
When I run AimStar 4.4.3 as an administrator or without an administrator, an error screen appears: Code execution cannot continue because libcur.dll was not found. Reinstalling the program to correct the problem

**Comment by AimDoesSkidding** [comment]
same

**Comment by lfajak2** [comment]
+1

**Comment by gabeyondiscord** [comment]
same

**Comment by M3351AN** [comment]
Place libcurl.dll in the same directory as aimstar.exe to temporarily solve the issue
[libcurl.zip](https://github.com/CowNowK/AimStar/files/15183839/libcurl.zip)
