### ISSUE TITLE
[ERROR] Failed to get module address.

### ISSUE THREAD

**Issue by niecname** [CowNowK/AimStar#293]
i need a help to use aimStar. I just get this error.
![image](https://github.com/CowNowK/AimStar/assets/168720470/70078880-7adc-4947-9cc8-e64075646b90)

**Comment by OvertimeDev-Random** [comment]
Run as admin

**Comment by niecname** [comment]
> Run as admin

no work

**Comment by OvertimeDev-Random** [comment]
Do you have the libcurl.dll in the same location as the exe?

**Comment by niecname** [comment]
> Do you have the libcurl.dll in the same location as the exe?
yes but it dont help

**Comment by khayyamov** [comment]
yes lastest version not working at all
