### ISSUE TITLE
AimStar 4.4.3  -- VAC ban

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#297]
[AimStar 4.4.3]
Keep safe mode on at all times
Just got vac banned
Everyone should be careful
external insecurity

**Comment by VVoiddd** [comment]
You'll always have a risk of getting banned with a free cheat. If you want lower chances of getting banned either dont use strong aimbot, Or buy a cheat.

**Comment by darken-san** [comment]
The cheat is detected, it will cause black/zero trust before getting hammered by a VAC ban.

**Comment by darken-san** [comment]
> You'll always have a risk of getting banned with a free cheat. If you want lower chances of getting banned either dont use strong aimbot, Or buy a cheat.

What risk of getting banned? It is already detected, all the players who used it, will get VAC banned, VAC will just delay it for a few weeks so the system can catch more newcomers.
