### ISSUE TITLE
AS DETECTED BY VAC!

### ISSUE THREAD

**Issue by ENDERMANHEY** [CowNowK/AimStar#298]
While legit cheating i got banned by vac

**Comment by j621103** [comment]
me too

**Comment by ByteCorum** [comment]
Idk, just use safe mode

**Comment by ENDERMANHEY** [comment]
ok

**Comment by ByteCorum** [comment]
If you get banned in a safe mod, please let us know because the problem could be much more global

**Comment by j621103** [comment]
[AimStar 4.4.3]
Keep safe mode on at all times
Just got vac banned
Everyone should be careful
external insecurity

**Comment by j621103** [comment]
> 如果您在安全模式中被禁止，請告訴我們，因為問題可能是全球性的

[AimStar 4.4.3]
Keep safe mode on at all times
Just got vac banned
Everyone should be careful
external insecurity

**Comment by ByteCorum** [comment]
Idk
