### ISSUE TITLE
Vac ban

### ISSUE THREAD

**Issue by morenvi** [CowNowK/AimStar#299]
we are vac banned after this time even is safe mode on.. why? cuz after the big update the .. cheat whas not stop it that whas a bait from you developer.. all time when valve update it you stop it the cheat to work but when big update whas on you didn't stop it , when i saw big update and i opened the cheat and i see he work but not the functions of him only wh..and after a while wh not working only the crosshair and double jump i knew it i have a vac ban .. it not whas than it whas after almost 1 week .. i ask you why not stop the cheat like before? you work with valve at marketing? or what?

**Comment by aydineray** [comment]
yes, they work together. big companies did it all the time to take your money in an easy way

**Comment by M3351AN** [comment]
Yes, we are valve staffs, we made this cheat in order to punish cheaters

**Comment by VVoiddd** [comment]
> we are vac banned after this time even is safe mode on.. why? cuz after the big update the .. cheat whas not stop it that whas a bait from you developer.. all time when valve update it you stop it the cheat to work but when big update whas on you didn't stop it , when i saw big update and i opened the cheat and i see he work but not the functions of him only wh..and after a while wh not working only the crosshair and double jump i knew it i have a vac ban .. it not whas than it whas after almost 1 week .. i ask you why not stop the cheat like before? you work with valve at marketing? or what?



yea, they 100% work with valve. Maybe not use a free cheat if you're worried about getting VAC'd, get a paid cheat. Even with a paid cheat you can still get banned, But the chances as far as im aware are lower than using a free cheat

**Comment by morenvi** [comment]
shame for what? are you not ashamed to be here? so i played with free cheats in past and not get banned the title "undetected" to that cheat whas true here is not , so to trusted cheat wanna all now are closed groups not public only with invitation can go there so gtfo with your title "undetected"

**Comment by morenvi** [comment]
btw i not blame dev for ban.. i blame them for not stop the cheat work when update coming

**Comment by M3351AN** [comment]
> shame for what? are you not ashamed to be here? so i played with free cheats in past and not get banned the title "undetected" to that cheat whas true here is not , so to trusted cheat wanna all now are closed groups not public only with invitation can go there so gtfo with your title "undetected"

chk commit 90a2cd8 line 11&23
and visit https://aimstar.bcow.top/ see what we warn
and, we never stop cheat from working mannually after any updates. 
im 2 lazy to explain why cheat always stop working to somebody like u, chk commit history of repo https://github.com/a2x/cs2-dumper and get the answer

**Comment by morenvi** [comment]
> > shame for what? are you not ashamed to be here? so i played with free cheats in past and not get banned the title "undetected" to that cheat whas true here is not , so to trusted cheat wanna all now are closed groups not public only with invitation can go there so gtfo with your title "undetected"
> 
> chk commit [90a2cd8](https://github.com/CowNowK/AimStar/commit/90a2cd862d0dab7a1d95fa24443d02a260bf2e8e) line 11&23 and visit https://aimstar.bcow.top/ see what we warn and, we never stop cheat from working mannually after any updates. im 2 lazy to explain why cheat always stop working to somebody like u, chk commit history of repo https://github.com/a2x/cs2-dumper and get the answer

well you missunderstand , i know ... i can have vac ban , but my question is why this version .3 it not whas stop it to launch when update valve whas there ,  last versions of cheat whas stoped from working cuz updates whas there so my question again is why that version whas not get stopp it to prevent valve collecting logs cuz you know all peeps who use this cheats whas played with that and that's whas a massive ban from that , before version .4 all versions whas stoped to be injected instead version .4 so?answear can ? or not?

**Comment by M3351AN** [comment]
> > > shame for what? are you not ashamed to be here? so i played with free cheats in past and not get banned the title "undetected" to that cheat whas true here is not , so to trusted cheat wanna all now are closed groups not public only with invitation can go there so gtfo with your title "undetected"
> > 
> > 
> > chk commit [90a2cd8](https://github.com/CowNowK/AimStar/commit/90a2cd862d0dab7a1d95fa24443d02a260bf2e8e) line 11&23 and visit https://aimstar.bcow.top/ see what we warn and, we never stop cheat from working mannually after any updates. im 2 lazy to explain why cheat always stop working to somebody like u, chk commit history of repo https://github.com/a2x/cs2-dumper and get the answer
> 
> well you missunderstand , i know ... i can have vac ban , but my question is why this version .3 it not whas stop it to launch when update valve whas there , last versions of cheat whas stoped from working cuz updates whas there so my question again is why that version whas not get stopp it to prevent valve collecting logs cuz you know all peeps who use this cheats whas played with that and that's whas a massive ban from that , before version .3 all versions whas stoped to be injected instead version .3 so?answear can ? or not?

"we never stop cheat from working mannually after any updates."
In other words, cheat stop working only due to valve update changed offsets, and that is why cheat stop working before version.3.
If offsets did not changed, cheat will not stop working, even if we know valve may collect logs
