### ISSUE TITLE
[QUESTION] Who's on ban list?

### ISSUE THREAD

**Issue by music-cat-bread** [CowNowK/AimStar#302]
So I've been pooking around and found that there's what   url calls a "drm", [here](https://github.com/CowNowK/AimStar/commit/55aa006d75cd0b3d5737dfc8d337145cbe292cd7#diff-31231d505b6a5b1561a04435e410977a923a56b127be81543c077371f627aafeR76) and [here](https://github.com/CowNowK/AimStar/commit/55aa006d75cd0b3d5737dfc8d337145cbe292cd7#diff-4c1046d703ffc96a1b4fbedf9291471391ab65c9d6520d7fd5423536f290431eR116).  

From ban list [here](https://gh-proxy.com/https://raw.githubusercontent.com/South-Haruna-Institute-of-Technology/timebase-otp/main/drm) it seems there are 4 people banned from using AimStar.
```
[
    "6849B94196811506",
    "5D67EA1081001185",
    "83816361F3765510",
    "715BA68534160023"
]
```

Out of curiocity, are those hwids of chineese resellers or someone else?
(Also wouldn't wiping all connected drives be slightly more effective?)

**Comment by M3351AN** [comment]
yes, they are Chinese reseller‘s we have known right now

**Comment by M3351AN** [comment]
and wOur purpose in joining this mechanism is to prevent them from further illegal resale, but we do not want to perform more aggressive operations because this may involve moral condemnation and legal issues in some countries.

**Comment by M3351AN** [comment]
We don't want this mechanism to be known by illegal resellers who know nothing about programming, so I edited your issue, please forgive me
