### ISSUE TITLE
AimStar Loader

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#303]
What function does this have?
Can he evade VAC detection?
Many people have been vac banned recently

**Comment by t0int** [comment]
otp doesnt work

**Comment by M3351AN** [comment]
idk at all since i can not understand epl code😵
![Image_1715527230884](https://github.com/CowNowK/AimStar/assets/65479796/37e4ac06-f202-4be3-812c-89a450baae5e)

**Comment by Sigma12456** [comment]
update offsets
