### ISSUE TITLE
why this cheat not working at all in the latest version

### ISSUE THREAD

**Issue by khayyamov** [CowNowK/AimStar#310]

**Comment by Sigma12456** [comment]
update offsets

**Comment by khayyamov** [comment]
@Sigma12456 
could you please show me an video or article to do that i khow there is file in this project named as affsets.h it have many hex value but I don't khow how to find offsets in game there is tools to find them ?

**Comment by M3351AN** [comment]
> @Sigma12456 could you please show me an video or article to do that i khow there is file in this project named as affsets.h it have many hex value but I don't khow how to find offsets in game there is tools to find them ?

all offsets are contained here https://github.com/CowNowK/AimStar/tree/main/CS2_External/a2x
and u can get latest one here
https://github.com/a2x/cs2-dumper/tree/main/output

**Comment by khayyamov** [comment]
![Screenshot 2024-05-18 185423](https://github.com/CowNowK/AimStar/assets/72504271/3417e963-3fbb-4c80-83de-e133bd7816b9)

**Comment by M3351AN** [comment]
> thank you hero for you help
> 
> ![Screenshot 2024-05-18 185423](https://private-user-images.githubusercontent.com/72504271/331811687-3417e963-3fbb-4c80-83de-e133bd7816b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDY3MzUsIm5iZiI6MTcxNjA0NjQzNSwicGF0aCI6Ii83MjUwNDI3MS8zMzE4MTE2ODctMzQxN2U5NjMtM2ZiYi00YzgwLTgzZGUtZTEzM2JkNzgxNmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE1MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZGZkOTkxYzFlMzVhMjBlNzU0NTEwNDBiM2U4ODlmNDcxNjkwYzkwY2YzZTlhYjk3MWFhYzcyODg5N2RiMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u2_ol0SgUczwL-LXfcDYBuNEAzJ3Cvo3JektsfWtRa8)
> 
> I think [last ](https://github.com/CowNowK/AimStar/releases/download/autobuild/AimStar-LLVM-Autobuild.zip) version not wokring for me ): my cs2 running in the background I test on libcurl x86 and 64 it show me same result

using this https://github.com/CowNowK/AimStar/releases/download/v4.4.3/libcurl.dll

**Comment by khayyamov** [comment]
Oh wow worked I think I should take an IQ test😂

**Comment by infinitel1nlove** [comment]
The newest patch 4.4.4 isnt working it just closed after otp was out in

**Comment by khayyamov** [comment]
@infinitel1nlove 
I think I put the Loader.exe and AimStar lastest release and libcurl all to one directory and run Loader it working
