### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dorlander** [CowNowK/AimStar#320]
without errors just this

![image](https://github.com/CowNowK/AimStar/assets/61416392/fcab52aa-4e08-40c6-aaa8-9a83099880f2)

and then close idk

**Comment by alexkandy8** [comment]
I have the same

**Comment by Dorlander** [comment]
> Look at [this ](https://github.com/CowNowK/AimStar/issues/317)issue

to which folder?

**Comment by alexkandy8** [comment]
I have the same

> > Look at [this ](https://github.com/CowNowK/AimStar/issues/317)issue
> 
> to which folder?

in the same folder as Loader

**Comment by Dorlander** [comment]
> I have the same
> 
> > > Look at [this ](https://github.com/CowNowK/AimStar/issues/317)issue
> > 
> > 
> > to which folder?
> 
> in the same folder as Loader

![image](https://github.com/CowNowK/AimStar/assets/61416392/7a15bab5-4ed5-4be2-bad5-5551cccd6f87)
didnt help

**Comment by alexkandy8** [comment]
Same, it didn't help me 
 :(

**Comment by Dorlander** [comment]
> Same, it didn't help me :(

lol why u answer then

**Comment by alexkandy8** [comment]
Because this issue is closed, than maybe it help other people
sorry for my eng

**Comment by Nx0Ri** [comment]
![pfp](https://github.com/CowNowK/AimStar/assets/152011726/4f53d84d-40bf-48be-9a92-058fb7e6f8e7)
