### ISSUE TITLE
I just got vac banned using AimStar Loader.

### ISSUE THREAD

**Issue by j621103** [CowNowK/AimStar#324]
![IMG_7291](https://github.com/CowNowK/AimStar/assets/130594594/55a2ddb5-3101-4aff-ad8d-b207234c85b7)

Played for about two days
[Loader.v1.1.0.zip]
5de8cdde47b0902babb93c0553a008baa70e47a1
The vac can still detect it
Everyone should pay attention

**Comment by DingusITMan** [comment]
buddy this is a free cheat like what do u expect
