### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by jhonthedoe** [CowNowK/AimStar#326]
sigs and offsets should be update

**Comment by diablo3fan** [comment]
agree ive tried with the new offset code but i cant get it to work can you update the client im on 4.4.3 cuase the others dont work please ?

**Comment by M3351AN** [comment]
a2x issue
https://github.com/a2x/cs2-dumper/issues/154
i have no time update now,sry

**Comment by diablo3fan** [comment]
all good

**Comment by diablo3fan** [comment]
![image](https://github.com/CowNowK/AimStar/assets/112856935/cf7815b2-c149-4dcd-a080-c45ac528f985)

**Comment by diablo3fan** [comment]
fix??

**Comment by diablo3fan** [comment]
nvm i did it it took a while but i fixed it

**Comment by diablo3fan** [comment]
bomb timer work but nothing else does

**Comment by diablo3fan** [comment]
> ![image](https://private-user-images.githubusercontent.com/112856935/333450930-cf7815b2-c149-4dcd-a080-c45ac528f985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mjg5MzcsIm5iZiI6MTcxNjUyODYzNywicGF0aCI6Ii8xMTI4NTY5MzUvMzMzNDUwOTMwLWNmNzgxNWIyLWMxNDktNGRjZC1hMDgwLWM0NWFjNTI4Zjk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNTMwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWI2ZjVlZDgwMWM2OGJlNDFkNDcwNTY0YTAwZDY5MDNlOTU2Yjc5OTIwY2RiNGM4YTIyMzczODIxZjAzZDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2F82mMtFAOvuzTtSqa-AktohClvfdOPiZz4JZeeuAM8)

i fixed the issue but only misc works like bomb timer fast stop no esp no rader nothing else works ???
