### ISSUE TITLE
latest build not working

### ISSUE THREAD

**Issue by khayyamov** [CowNowK/AimStar#327]
It seems that the program can't create the offsets.json and buttons.json files. I created them manually, but there is a problem in parse json.

this error throwing because offsets not initiated 

JSON parsing error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
JSON parsing error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
Error: [json.exception.type_error.305] cannot use operator[] with a string argument with array

![Screenshot 2024-05-24 111855](https://github.com/CowNowK/AimStar/assets/72504271/4b6be70d-53c8-470e-b758-f3166efe590b)

**Comment by MaYecha** [comment]
how did u solved it?
