### ISSUE TITLE
Failed to locate offsets directory

### ISSUE THREAD

**Issue by lfajak2** [CowNowK/AimStar#333]
`Failed to locate offsets directory: C:\Users\Admin\Documents\AimStar\Offsets`
How to fix?

**Comment by zsui2354** [comment]
我想你是没有在Aimstar配置文件中创建 Offsets文件夹 ，创建后将 json格式的偏移量 文件放进去,一共是 2个文件 offsets.json ，buttons.json ，但你现在没必要去做 ， 等最新的偏移量更新后在做

**Comment by CowNowK** [comment]
![image](https://github.com/CowNowK/AimStar/assets/133740174/ed84dce2-52c1-4188-8749-597e6a2bc9c9)
[buttons.json](https://github.com/a2x/cs2-dumper/blob/main/output/buttons.json), [offsets.json](https://github.com/a2x/cs2-dumper/blob/main/output/offsets.json)
