### ISSUE TITLE
Triggerbot not working

### ISSUE THREAD

**Issue by kura6789** [CowNowK/AimStar#344]
How to fix triggerbot?
after this line 	if (!ProcessMgr.ReadMemory<DWORD>(LocalEntity.Pawn.Address + Offset::Pawn.iIDEntIndex, uHandle))
		std::cout << uHandle << std::endl;
uHandle  is still =0

**Comment by M3351AN** [comment]
it is working now
uHandle should be -1 if no entity on crosshair, and it would changed when aim at hittable entities
