### ISSUE TITLE
为什么点任何按键都无法进入，他会闪退

### ISSUE THREAD

**Issue by 6KKK6** [CowNowK/AimStar#346]
![IMG_20240530_181313](https://github.com/CowNowK/AimStar/assets/128572343/9c8c53ce-10b1-4e90-96a7-8db2a5bac103)

**Comment by CowNowK** [comment]
## Failed to locate offsets folder:
1. Download the offsets files from a2x's repo: [buttons.json](https://github.com/a2x/cs2-dumper/blob/main/output/buttons.json), [offsets.json](https://github.com/a2x/cs2-dumper/blob/main/output/offsets.json)
2. Copy and paste into `Documents\AimStar\Offsets\`, if the game is updated in the future, update the offsets file by yourself
