### ISSUE TITLE
OTP Code Generator Site Error

### ISSUE THREAD

**Issue by koyande360** [CowNowK/AimStar#360]
https://aimstar.tkm.icu/ OTP code generator of Aimstar CS2 
Fix this, I can't access to this site to generate OTP for the latest build.

![Screenshot 2024-06-14 005740](https://github.com/CowNowK/AimStar/assets/159618883/e32ac4da-7141-4b5a-b199-36ab70a6e0c8)

**Comment by mildnsj** [comment]
Hello.

I don't face any issues using the site myself, you could also go advanced->continue anyways, it should still work.

Kind regards.

**Comment by M3351AN** [comment]
ssl cert fixed

**Comment by M3351AN** [comment]
![image](https://github.com/CowNowK/AimStar/assets/65479796/072fde28-75fb-446f-8d53-f786ac77edb7)
