### ISSUE TITLE
the cheat is woking but nothingh happens in the game

### ISSUE THREAD

**Issue by xBow5** [CowNowK/AimStar#361]
![image](https://github.com/CowNowK/AimStar/assets/160162315/fd58a517-57b5-40d0-8ee0-e6d23725116e)

**Comment by vivabonito** [comment]
Yes, new update just came in. offsets.yaml needs to be updated again.

**Comment by M3351AN** [comment]
offset.yaml can be updated now
https://aimstar.tkm.icu/updater
