### ISSUE TITLE
OTP Problem 

### ISSUE THREAD

**Issue by FUKYAH** [CowNowK/AimStar#363]
Where to get OTP CODE Thank you!

**Comment by hitttt32** [comment]
probably the otp code website was hacked
it is sent to the telegram website a bitcoin website
a random website ?????

**Comment by M3351AN** [comment]
fixed,clean browser cache and refresh plz
cloudflare security setting issue

**Comment by FUKYAH** [comment]
Hi Good Morning hi can you update the new offset of cs2 thanks ❤️ 
Because they update again thank you so much Aimstar always ❤️🙏

Yahoo Mail: Search, organise, conquer 
 
  On Mon, 17 Jun 2024 at 1:32 pm, ***@***.***> wrote:   


fixed,clean browser cache and refresh plz
cloudflare security setting issue

**Comment by Nx0Ri** [comment]
> Hi Good Morning hi can you update the new offset of cs2 thanks ❤️  Because they update again thank you so much Aimstar always ❤️🙏 Yahoo Mail: Search, organise, conquer On Mon, 17 Jun 2024 at 1:32 pm, ***@***.***> wrote: fixed,clean browser cache and refresh plz cloudflare security setting issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

no, use dumper

**Comment by FUKYAH** [comment]
Hii Aimstar please update the offset thank you so much the cheat don't work thank you so much for you time 🙏❤️

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 19 Jun 2024 at 5:10 pm, ***@***.***> wrote:   



Hi Good Morning hi can you update the new offset of cs2 thanks ❤️  Because they update again thank you so much Aimstar always ❤️🙏 Yahoo Mail: Search, organise, conquer On Mon, 17 Jun 2024 at 1:32 pm, @.> wrote: fixed,clean browser cache and refresh plz cloudflare security setting issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


no, use dumper
