### ISSUE TITLE
RCS is not working

### ISSUE THREAD

**Issue by Bomborasclay** [CowNowK/AimStar#369]
No recoil option is not working at all, was working days ago but now is not functioning

**Comment by M3351AN** [comment]
https://aimstar.tkm.icu/updater

After testing, updating the offset can solve this problem

**Comment by M3351AN** [comment]
![image](https://github.com/CowNowK/AimStar/assets/65479796/3b71dbc3-e67b-4075-a336-ea6fa7fc96f1)
