### ISSUE TITLE
Fov and aim doesn't work

### ISSUE THREAD

**Issue by RobloxExecutorV3** [CowNowK/AimStar#370]
![image](https://github.com/CowNowK/AimStar/assets/155648690/962558ba-a33c-4d2f-8c49-3bc6b2fdcd42)

**Comment by RobloxExecutorV3** [comment]
there is no fov on screen

**Comment by RobloxExecutorV3** [comment]
in exloader version all work

**Comment by M3351AN** [comment]
This may sound weird, but just updating the offsets can solve the problem
https://aimstar.tkm.icu/updater
![image](https://github.com/CowNowK/AimStar/assets/65479796/80503a0d-30ca-4482-b9e4-0d92f098cbb0)
