### ISSUE TITLE
Regarding Aimbot

### ISSUE THREAD

**Issue by DAZstar** [CowNowK/AimStar#376]
What should I change if I want to aimbot my teammates instead of enemy? Can't seem to find where you had choosen  enemy in the source. Sorry I am a bit new.

**Comment by Baffy** [comment]
> What should I change if I want to aimbot my teammates instead of enemy? Can't seem to find where you had choosen enemy in the source. Sorry I am a bit new.

what the heck ..you want to use it in deathmatch ? XD

**Comment by CowNowK** [comment]
Disable teamcheck in misc page

**Comment by elegydev** [comment]
Hey for some reason when I open user aimstar nothing shows
