### ISSUE TITLE
new update of game

### ISSUE THREAD

**Issue by stormzzyy** [CowNowK/AimStar#378]
aimstar is curently not working due to a game update i think the offsets might updated

**Comment by primewk** [comment]
yeah

**Comment by phoneixdevv** [comment]
I updated the offsets by my self but it doesn't work

edit: in the offsets.yaml the numbers are dec, 0xhexnumbers on offsets.h in a2x or ur dump file u need to convert the hexnumbers to dec and replace them in offsets.yaml u can convert them through calculator actually

**Comment by primewk** [comment]
[offsets.txt](https://github.com/user-attachments/files/17118249/offsets.txt)
Rename it to `offsets.yaml` and put it in your `Aimstar/Offsets` folder.
Should work
