### ISSUE TITLE
Current map name

### ISSUE THREAD

**Issue by tewshi0** [CowNowK/AimStar#379]
How do you get current map name? 
I tried getting it using globalvars::GetCurrentMapName() but it crashes the program

The commented out code at 
https://github.com/CowNowK/AimStar/blob/65c01e284f29a28754ebf9934d6ce4f3a5d5e744/CS2_External/Cheats.cpp#L194-L200 seems to be based on https://www.unknowncheats.me/forum/4166432-post2.html which also crashes the program.

**Comment by M3351AN** [comment]
i have not figured out what's wrong, so i have no idea how to fetch current mapname.that's why estim bomb damage isnot always correct.

**Comment by M3351AN** [comment]
globalvars from a2x returns pointer of globalvars
anyway, current struct can fetch proper tickcount,currenttime etc. but address of current map still looks is not right

**Comment by tewshi0** [comment]
here's how it worked

I decided to follow an approach shared later in the same thread to read map name char by char and and it worked perfectly. (https://www.unknowncheats.me/forum/4198420-post17.html)
```
	char currentChar;
	for (int i = 0; i < 32; i++) {
		ProcessMgr.ReadMemory<char>(Global_Vars.m_current_mapname + i, currentChar);
		if (currentChar >= 32 && currentChar <= 126) {
			MapName += currentChar;
		}
		else {
			break;
		}
	}
```
I looked at memory code of some codebases on how they read string. https://github.com/Exlodium/CS2-External-Base/blob/d02cc0eeb0fef30d56cbca78a4905288cd301b77/src/memory/Memory.h#L113
So I implemented a ReadString function under ProcessManager
```
	std::string ReadString(DWORD64 address, size_t maxLength = 256)
	{
		std::vector<char> buffer(maxLength, 0);

		if (!ReadMemory<char>(address, buffer[0], maxLength)) {
			return "**invalid**";
		}

		buffer[maxLength - 1] = '\0';

		size_t actualLength = 0;
		while (actualLength < maxLength && buffer[actualLength] != '\0') {
			++actualLength;
		}

		return std::string(buffer.data(), actualLength);
	}
```
and now we can simply read the map name using
```
MapName = ProcessMgr.ReadString(Global_Vars.m_current_mapname, 32);
```

**Comment by M3351AN** [comment]
ty, works well. i ll impl it
