### ISSUE TITLE
New CS2 Update [THE ARMORY] 

### ISSUE THREAD

**Issue by slygm01** [CowNowK/AimStar#380]
Hi there, I have tried to use the latest offsets.yaml file generated from https://aimstar.tkm.icu/updater. It seems like it's not working, the hack menu was showing, but the esp is not functioning. 

Please enlighten me if I miss out any steps. 

This is the offsets.yaml version I generated:
https://pastebin.com/FaFuGZ20

**Comment by ShobitX** [comment]
Nothing works please solve it

**Comment by ShobitX** [comment]
How much time it take

**Comment by M3351AN** [comment]
seems latest release fixed crash, and functions working
