### ISSUE TITLE
i can't compile with ring0

### ISSUE THREAD

**Issue by elementcheats** [CowNowK/AimStar#386]
As I writed in the title, I cannot compile with ring0. I get the error "Cannot open input file Utils\kdm\kdmapper_lib-Release.lib". Where can I get the necessary libraries?

**Comment by Gktwo** [comment]
search kdmapper on github

**Comment by M3351AN** [comment]
u have to build kdmapper lib by ur self, since im not sure if original kdmapper repo is suitable for all windows versions
