### ISSUE TITLE
Failed to locate offsets file

### ISSUE THREAD

**Issue by fsdagsgdsvvsh** [CowNowK/AimStar#398]
![resim_2024-10-17_003729569](https://github.com/user-attachments/assets/07a50533-860c-4d38-9971-b97d5716ebf5)
Write success
[<] Loading vulnerable driver, Name: kffbBZVtfQIzWDBatbzQNj
[+] NtLoadDriver Status 0xc0000603
[-] Your vulnerable driver list is enabled and have blocked the driver loading, you must disable vulnerable driver list to use kdmapper with intel driver
[-] Registry path to disable vulnerable driver list: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Config
[-] Set 'VulnerableDriverBlocklistEnable' as dword to 0
[-] Failed to register and start service for the vulnerable driver

    ___    _          _____ __
   /   |  (_)___ ___ / ___// /_____ ______
  / /| | / / __ `__ \\__ \/ __/ __ `/ ___/
 / ___ |/ / / / / / /__/ / /_/ /_/ / /
/_/  |_/_/_/ /_/ /_/____/\__/\__,_/_/

Build-Aug 14 2024-20:49:28
0
2CDD01E846889683
Failed to locate offsets file: C:\Users\memog\OneDrive\Belgeler\AimStar\Offsets\offsets.yaml
[ERROR] Failed to update offsets.
Press any key to continue . . .

**Comment by CowNowK** [comment]
[Download offsets file](https://aimstar.tkm.icu/updater)

**Comment by CowNowK** [comment]
Also
[-] Registry path to disable vulnerable driver list: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Config
[-] Set 'VulnerableDriverBlocklistEnable' as dword to 0
