### ISSUE TITLE
what should I do?

### ISSUE THREAD

**Issue by fsdagsgdsvvsh** [CowNowK/AimStar#401]
![image](https://github.com/user-attachments/assets/a3527e13-7dd7-405e-8e7f-93f58a97a971)
![resim_2024-10-17_145856555](https://github.com/user-attachments/assets/cf0b1f14-d90c-4adb-a709-69db5b93556d)

**Comment by CowNowK** [comment]
![image](https://github.com/user-attachments/assets/2447bb83-0cf9-43fa-93d7-90a918e869a9)
