### ISSUE TITLE
Aimbot and esp not working

### ISSUE THREAD

**Issue by dargan1101** [CowNowK/AimStar#405]
I have downloaded the most recent version of the cheat but it is still not working.

**Comment by TilapiaLog** [comment]
check your esp setting，Hotkey launch is the default mode，set it to always active

**Comment by TilapiaLog** [comment]
> check your esp setting，Hotkey launch is the default mode，set it to always active

**Comment by fsdagsgdsvvsh** [comment]
where esp settings

**Comment by CowNowK** [comment]
if u see that
![QQ_1729407106388](https://github.com/user-attachments/assets/953184a7-12af-473c-bb22-f952d167bd9f)
