### ISSUE TITLE
在把ESP设置为always active时，哪怕关闭了整个ESP，效果仍然存在

### ISSUE THREAD

**Issue by TilapiaLog** [CowNowK/AimStar#406]

**Comment by TilapiaLog** [comment]
![Uploading 168bbaa5-8eec-4f76-bbac-a8de197a985a.png…]()

**Comment by TilapiaLog** [comment]
新发现，同样是这个开关的问题，在反复开关总开关和always active开关时（比如先开启总开关，再打开active开关，直接关闭总开关，再打开总开关，再开关一次active），可能会导致esp彻底失效，重启软件才能生效

**Comment by CowNowK** [comment]
Fixed
