### ISSUE TITLE
It's the weekend! It's time for an update

### ISSUE THREAD

**Issue by AtTbufeiwan** [CowNowK/AimStar#71]
It's the weekend! It's time for an update

**Comment by Nx0Ri** [comment]
the bruh moment

**Comment by Nx0Ri** [comment]
cant u wait

**Comment by walter11av** [comment]
How often does valve change the offsets?

**Comment by AtTbufeiwan** [comment]
> How often does valve change the offsets?

I think he might need to change it every two months

**Comment by CowNowK** [comment]
> How often does valve change the offsets?

every game update
