### ISSUE TITLE
some features are broken

### ISSUE THREAD

**Issue by walter11av** [CowNowK/AimStar#75]
I tried it: glow, aimbot and spec list not work properly

**Comment by walter11av** [comment]
its possible add aimbot hold key mode too?

**Comment by Nx0Ri** [comment]
Bruh, there's hold mode is enabled by default

**Comment by walter11av** [comment]
> Bruh, there's hold mode is enabled by default

At first it was in hold mode, but now it is in switch mode, you have to press the key again to deactivate

I hope I was specific
