### ISSUE TITLE
Fix detected cheat

### ISSUE THREAD

**Issue by Laranjo1** [CowNowK/AimStar#76]
I have the slight impression that this cheat is using open process to edit memory instead of creating a handle reference for this purpose and that's why it's probably giving vac

**Comment by vsaint1** [comment]
nop the cheat is sigscanned by vac, + cheat has a lot of users ( free ) and insane hackers are selling aimstar/tkazer forks...

**Comment by ChiefG** [comment]
> nop the cheat is sigscanned by vac, + cheat has a lot of users ( free ) and insane hackers are selling aimstar/tkazer forks...

Than why im still not banned ? 😂

**Comment by Laranjo1** [comment]
> nop the cheat is sigscanned by vac, + cheat has a lot of users ( free ) and insane hackers are selling aimstar/tkazer forks...

It's not detected because sigscanned

**Comment by zeroy2891** [comment]
if u use glow its 100% bad trust
