### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ShavoyMartin** [CowNowK/AimStar#84]
Can anyone tell me why this cheat is laggy asf and doesnt work ? the esp is literally a slideshow and the aimbot doesnt work because its laggy, how do i fix this ? I use Undetek v4 now cause it actually works but the esp and aimbot on that is ass so i wanna stop using it and move here but its lagy can anyone fix this ???

**Comment by CowNowK** [comment]
It works perfectly on my pc, please check ->[Wiki](https://github.com/CowNowK/AimStar/wiki/Gaming-Issue#3-laggy-esp)
