### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by MatthiasHauser** [CowNowK/AimStar#85]
Hi,

after building and running the system prints its running; but then it instantly throws an assertion error in the imgui and crashes. anyone has an idea why?

Assertion failed: SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!", file D:\AimStar\CS2_External\OS-ImGui\imgui\imgui.cpp, line 9273

edit: when i comment the assertion, the program starts , and gui is visible in borderless mode; but the gui isnt responding to input

**Comment by CowNowK** [comment]
any screenshots?

**Comment by FasTer69** [comment]
u probably deleted some piece of code where is definated PopID or TreePop

**Comment by Loengames** [comment]
![изображение_2024-01-09_121926189](https://github.com/CowNowK/AimStar/assets/79316796/fccd0781-1142-48a7-967d-ebe03d9b0bc0)
I have this problem too!

**Comment by FasTer69** [comment]
> ![изображение_2024-01-09_121926189](https://private-user-images.githubusercontent.com/79316796/295174626-fccd0781-1142-48a7-967d-ebe03d9b0bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDY0MzYsIm5iZiI6MTcwNDgwNjEzNiwicGF0aCI6Ii83OTMxNjc5Ni8yOTUxNzQ2MjYtZmNjZDA3ODEtMTE0Mi00OGE3LTk2N2QtZWJlMDNkOWIwYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzMTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjEwMjY3NTYyZjgzZDZiNGExYzhiMmVmZmQ1OGUyNTI4YWUzMjdiMjNhYTQ4YmQ0ODBhNjNmMTg1ZmE4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndPL5m4rHA-bt6rKg8tSMUVwQSUh8yl_itZT7cxr2lM) I have this problem too!

did u build on release?

**Comment by Loengames** [comment]
Yes! I installed from here: https://github.com/CowNowK/AimStar/releases/tag/3.6

**Comment by CowNowK** [comment]
> > Yes! I installed from here: https://github.com/CowNowK/AimStar/releases/tag/3.6
> 
> oh sorry i thaught u was building it yourself, if this error occurs when u downloaded release version try building it yourself

Try debugging in `release x64`

**Comment by CowNowK** [comment]
Build in `Release x64`
