### ISSUE TITLE
I have made a nice style of cheat menu. But I don't know how to insert it correctly!

### ISSUE THREAD

**Issue by Loengames** [CowNowK/AimStar#92]

**Comment by CowNowK** [comment]
Set the window background color to transparent, the window size corresponds to your image, then load your image at the bottom

**Comment by Loengames** [comment]
I understand correctly that the image should be added to the Style.h file load and then all this should be configured in the GUI.h file?

**Comment by CowNowK** [comment]
Added to the `Image.h` file not `Style.h`, and you should be able to find how other images are configured at the beginning of the `GUI.h` file

**Comment by Loengames** [comment]
Thank you so much.
