### ISSUE TITLE
How to convert image

### ISSUE THREAD

**Issue by Marcis2** [CowNowK/AimStar#98]
Hello, I would like to know how are you converting images to unsigned char[], thanks in advance and nice project!

**Comment by JannesBonk** [comment]
> Hello, I would like to know how are you converting images to unsigned char[], thanks in advance and nice project!

using a hex editor

**Comment by CowNowK** [comment]
> Hello, I would like to know how are you converting images to unsigned char[], thanks in advance and nice project!

HxD
